/* eslint-disable global-require */
export const home = require('../../image/home-icon-green.png')
export const expandButton = require('../../image/expand-arrow.png')
export const collapseButton = require('../../image/collapse-arrow.png')
export const jambLogo = require('../../image/jamb-logo.png')
export const brochure = require('../../image/menu.png')
export const cutoff = require('../../image/checklist.png')
export const center = require('../../image/center.png')
export const faq = require('../../image/question.png')
export const report = require('../../image/recommendation.png')
export const nuc = require('../../image/nuc.jpg')
export const student = require('../../image/student.jpeg')
export const thumb = require('../../image/thumb.jpeg')
export const kaduna = require('../../image/kaduna.jpeg')
export const sule = require('../../image/sule.jpg')
export const closeBtn = require('../../image/close.png')
export const plane = require('../../image/paper-plane.png')
export const background = require('../../image/university_students.jpg')
